package edu.monash.fit2024.simulator.matter;

import edu.monash.fit2024.simulator.userInterface.MessageRenderer;

/** Base class for simulator affordances, i.e. commands that are performed on an entity.
 * 
 * Generated by UML Lab.
 * 
 * @author ram
 * @date 17 February 2013
 */
/* Changelog
 * 2013-02-17: original version
 * 2013-02-27: renamed Command to Action (ram)
 * 2013-02-28: Now extends Action rather than implementing it, because Action is now a class. (ram)
 * 	Improved comments on constructors for the benefit of authors of client code. (ram)
 * 2013-03-08: Removed EntityInterface (ram)
 */


public abstract class Affordance extends Action {

		protected EntityInterface target; // grammatical object
		
		/**
		 * <p>This constructor is private to prevent Affordances being instantiated
		 * without setting a target.  If you don't need a target, you should extend Action
		 * instead.<p/>
		 * 
		 * <p>The "unused" warning is suppressed because the entire purpose of declaring this
		 * constructor private is to prevent its use.</p>
		 */
		private Affordance(MessageRenderer m) {super(m);}
		
		/**
		 * <p>Parameterized constructor.  Descendant classes should call this constructor
		 * explicitly to set the target, as the default constructor is declared private.</p>
		 * 
		 * @param theTarget Entity that has the Affordance
		 * @param m MessageRenderer to allow the Affordance to emit messages to user
		 */
		public Affordance(EntityInterface theTarget, MessageRenderer m) {
			super(m);
			target = theTarget;
		}


}
