package edu.monash.fit2024.simulator.space;

/**
 * Location: base class for simulated locations.
 * 
 * Generated by UML Lab.
 * 
 * @author ram
 * @date 17 February 2013
 */
/*
 * Changelog:
 * 2013-04-13: Factored Location.Maker out into a separate file, because the combination
 * 		of inner classes and generics was too much for Eclipse's tiny brain (ram)
 */

import java.util.Map;


public abstract class Location {

	protected Map<Direction, Location> neighbours;

	/**
	 * <p>Finds and returns neighbouring location in the specified direction</p>
	 * @param d the direction
	 * @return the neighbour in the specified direction, or null if no such neighbour exists
	 */
	public Location getNeighbour(final Direction d) {
		return neighbours.get(d);
	}

	/**
	 * <p>Adds a neighbour in the specified direction.</p>
	 * @param d direction
	 * @param l neighbouring location
	 * @return the neighbouring location
	 */
	public Location addNeighbour(final Direction d, final Location l) {
		return neighbours.put(d, l);
	}
	
	/**
	 * Returns true if and only if there is a Location adjacent to this one in the specified direction.
	 * @param d direction
	 * @return true if such a location exists, false otherwise
	 */
	public Boolean hasExit(final Direction d) {
		return neighbours.keySet().contains(d);
	}
	
}
